import type { DefinitionSeed } from './types';

/**
 * Definitions are frequently all-or-nothing marks, so each one carries the
 * plain statement *and* the phrasing an examiner expects where they differ.
 */
export const definitions: DefinitionSeed[] = [
  // --- Physics -------------------------------------------------------------
  { subject: 'physics', subtopicNumber: '1.1', term: 'Scalar quantity', statement: 'A quantity that has magnitude only.' },
  { subject: 'physics', subtopicNumber: '1.1', term: 'Vector quantity', statement: 'A quantity that has both magnitude and direction.' },
  { subject: 'physics', subtopicNumber: '1.2', term: 'Speed', statement: 'The distance travelled per unit time.' },
  { subject: 'physics', subtopicNumber: '1.2', term: 'Velocity', statement: 'Speed in a given direction, or the rate of change of displacement.' },
  { subject: 'physics', subtopicNumber: '1.2', term: 'Acceleration', statement: 'The change in velocity per unit time.' },
  {
    subject: 'physics',
    subtopicNumber: '1.2',
    term: 'Terminal velocity',
    statement: 'The constant velocity reached by a falling object when air resistance equals its weight.',
    examWording: 'The velocity at which the resultant force on a falling object is zero, so it no longer accelerates.',
  },
  { subject: 'physics', subtopicNumber: '1.3', term: 'Mass', statement: 'A measure of the quantity of matter in an object, measured in kilograms.' },
  {
    subject: 'physics',
    subtopicNumber: '1.3',
    term: 'Weight',
    statement: 'The force acting on an object due to a gravitational field.',
    examWording: 'The gravitational force on an object, W = mg, measured in newtons.',
  },
  { subject: 'physics', subtopicNumber: '1.4', term: 'Density', statement: 'Mass per unit volume.' },
  {
    subject: 'physics',
    subtopicNumber: '1.5',
    term: 'Moment of a force',
    statement: 'The turning effect of a force about a pivot.',
    examWording: 'Moment = force × perpendicular distance from the pivot.',
  },
  {
    subject: 'physics',
    subtopicNumber: '1.5',
    term: 'Principle of moments',
    statement:
      'For a body in equilibrium, the sum of the clockwise moments about any point equals the sum of the anticlockwise moments about that point.',
  },
  {
    subject: 'physics',
    subtopicNumber: '1.5',
    term: 'Limit of proportionality',
    statement: 'The point beyond which the extension of a spring is no longer directly proportional to the load.',
  },
  { subject: 'physics', subtopicNumber: '1.6', term: 'Momentum', statement: 'The product of mass and velocity, p = mv.' },
  {
    subject: 'physics',
    subtopicNumber: '1.7',
    term: 'Principle of conservation of energy',
    statement: 'Energy cannot be created or destroyed; it can only be transferred from one store to another.',
  },
  { subject: 'physics', subtopicNumber: '1.7', term: 'Work done', statement: 'The energy transferred when a force moves an object through a distance in the direction of the force.' },
  { subject: 'physics', subtopicNumber: '1.7', term: 'Power', statement: 'The rate of energy transfer, or the rate of doing work.' },
  { subject: 'physics', subtopicNumber: '1.7', term: 'Efficiency', statement: 'The fraction of the total input energy that is transferred usefully.' },
  { subject: 'physics', subtopicNumber: '1.8', term: 'Pressure', statement: 'Force per unit area.' },
  {
    subject: 'physics',
    subtopicNumber: '2.1',
    term: 'Evaporation',
    statement:
      'The escape of the more energetic particles from the surface of a liquid, which can occur at any temperature and cools the remaining liquid.',
  },
  {
    subject: 'physics',
    subtopicNumber: '2.2',
    term: 'Specific heat capacity',
    statement: 'The energy required to raise the temperature of 1 kg of a substance by 1 °C.',
  },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Wavelength', statement: 'The distance between two neighbouring points in phase on a wave, such as crest to crest.' },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Frequency', statement: 'The number of complete waves passing a point per second.' },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Amplitude', statement: 'The maximum displacement of a point on a wave from its undisturbed position.' },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Transverse wave', statement: 'A wave in which the oscillations are perpendicular to the direction of energy transfer.' },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Longitudinal wave', statement: 'A wave in which the oscillations are parallel to the direction of energy transfer.' },
  { subject: 'physics', subtopicNumber: '3.1', term: 'Diffraction', statement: 'The spreading of a wave as it passes through a gap or around an edge.' },
  {
    subject: 'physics',
    subtopicNumber: '3.2',
    term: 'Critical angle',
    statement: 'The angle of incidence in the denser medium for which the angle of refraction is 90°.',
  },
  {
    subject: 'physics',
    subtopicNumber: '3.2',
    term: 'Total internal reflection',
    statement:
      'The complete reflection of light back into a denser medium when the angle of incidence exceeds the critical angle.',
  },
  { subject: 'physics', subtopicNumber: '4.2', term: 'Electric current', statement: 'The rate of flow of electric charge.' },
  {
    subject: 'physics',
    subtopicNumber: '4.2',
    term: 'Potential difference',
    statement: 'The energy transferred per unit charge passing between two points in a circuit.',
    examWording: 'Work done per unit charge; one volt is one joule per coulomb.',
  },
  { subject: 'physics', subtopicNumber: '4.2', term: 'Resistance', statement: 'The ratio of potential difference across a component to the current through it.' },
  {
    subject: 'physics',
    subtopicNumber: '4.2',
    term: "Ohm's law",
    statement:
      'For a metallic conductor at constant temperature, the current through it is directly proportional to the potential difference across it.',
  },
  {
    subject: 'physics',
    subtopicNumber: '4.5',
    term: 'Electromagnetic induction',
    statement:
      'The production of an e.m.f. across a conductor when it cuts magnetic field lines, or when the magnetic field through a coil changes.',
  },
  { subject: 'physics', subtopicNumber: '5.1', term: 'Proton number', statement: 'The number of protons in the nucleus of an atom.' },
  { subject: 'physics', subtopicNumber: '5.1', term: 'Nucleon number', statement: 'The total number of protons and neutrons in the nucleus of an atom.' },
  {
    subject: 'physics',
    subtopicNumber: '5.2',
    term: 'Half-life',
    statement: 'The time taken for half the radioactive nuclei in a sample to decay.',
    examWording: 'The time taken for the activity (count rate) of a sample to fall to half its initial value.',
  },
  {
    subject: 'physics',
    subtopicNumber: '5.2',
    term: 'Background radiation',
    statement: 'The low level of ionising radiation always present from natural and artificial sources in the environment.',
  },

  // --- Chemistry -----------------------------------------------------------
  {
    subject: 'chemistry',
    subtopicNumber: '1.2',
    term: 'Diffusion',
    statement:
      'The net movement of particles from a region of higher concentration to a region of lower concentration, resulting from their random motion.',
  },
  { subject: 'chemistry', subtopicNumber: '2.1', term: 'Element', statement: 'A substance made of only one type of atom, which cannot be broken down chemically.' },
  { subject: 'chemistry', subtopicNumber: '2.1', term: 'Compound', statement: 'A substance in which two or more different elements are chemically combined in fixed proportions.' },
  { subject: 'chemistry', subtopicNumber: '2.1', term: 'Mixture', statement: 'Two or more substances that are not chemically combined and can be separated by physical means.' },
  {
    subject: 'chemistry',
    subtopicNumber: '2.3',
    term: 'Isotopes',
    statement: 'Atoms of the same element with the same number of protons but different numbers of neutrons.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '2.4',
    term: 'Ionic bond',
    statement: 'The strong electrostatic attraction between oppositely charged ions.',
    examWording: 'The electrostatic attraction between oppositely charged ions formed by the transfer of electrons.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '2.5',
    term: 'Covalent bond',
    statement: 'A shared pair of electrons between two atoms.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '2.7',
    term: 'Metallic bonding',
    statement:
      'The electrostatic attraction between a lattice of positive metal ions and a sea of delocalised electrons.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '3.2',
    term: 'Relative atomic mass',
    statement:
      'The average mass of the isotopes of an element, compared with 1/12 of the mass of an atom of carbon-12.',
  },
  { subject: 'chemistry', subtopicNumber: '3.3', term: 'Mole', statement: 'The amount of substance containing 6.02 × 10²³ particles (the Avogadro constant).' },
  { subject: 'chemistry', subtopicNumber: '3.3', term: 'Empirical formula', statement: 'The simplest whole-number ratio of the atoms of each element in a compound.' },
  {
    subject: 'chemistry',
    subtopicNumber: '4.1',
    term: 'Electrolysis',
    statement:
      'The breakdown of an ionic compound, when molten or in aqueous solution, by the passage of electricity.',
  },
  { subject: 'chemistry', subtopicNumber: '4.1', term: 'Electrolyte', statement: 'A molten or dissolved ionic compound that conducts electricity and is broken down by it.' },
  {
    subject: 'chemistry',
    subtopicNumber: '5.1',
    term: 'Exothermic reaction',
    statement: 'A reaction that transfers energy to the surroundings, so the temperature of the surroundings rises and ΔH is negative.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '5.1',
    term: 'Endothermic reaction',
    statement: 'A reaction that takes in energy from the surroundings, so the temperature of the surroundings falls and ΔH is positive.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '5.1',
    term: 'Activation energy',
    statement: 'The minimum energy that colliding particles must have for a reaction to occur.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '6.2',
    term: 'Catalyst',
    statement:
      'A substance that increases the rate of a reaction by providing an alternative pathway with a lower activation energy, and is not used up in the reaction.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '6.3',
    term: 'Dynamic equilibrium',
    statement:
      'The state in a closed system where the forward and reverse reactions occur at the same rate, so the concentrations of reactants and products remain constant.',
  },
  { subject: 'chemistry', subtopicNumber: '6.4', term: 'Oxidation', statement: 'The loss of electrons (or gain of oxygen), causing an increase in oxidation number.' },
  { subject: 'chemistry', subtopicNumber: '6.4', term: 'Reduction', statement: 'The gain of electrons (or loss of oxygen), causing a decrease in oxidation number.' },
  {
    subject: 'chemistry',
    subtopicNumber: '7.1',
    term: 'Acid',
    statement: 'A substance that produces H⁺ ions in aqueous solution; a proton donor.',
  },
  { subject: 'chemistry', subtopicNumber: '7.1', term: 'Base', statement: 'A substance that neutralises an acid to form a salt and water; a proton acceptor.' },
  { subject: 'chemistry', subtopicNumber: '7.1', term: 'Alkali', statement: 'A soluble base that produces OH⁻ ions in aqueous solution.' },
  {
    subject: 'chemistry',
    subtopicNumber: '7.1',
    term: 'Strong acid',
    statement: 'An acid that is fully dissociated into ions in aqueous solution.',
    examWording: 'Completely ionised in solution — distinct from "concentrated", which describes amount per volume.',
  },
  { subject: 'chemistry', subtopicNumber: '7.1', term: 'Weak acid', statement: 'An acid that is only partially dissociated into ions in aqueous solution.' },
  { subject: 'chemistry', subtopicNumber: '7.2', term: 'Amphoteric oxide', statement: 'An oxide that reacts with both acids and bases to form a salt and water.' },
  {
    subject: 'chemistry',
    subtopicNumber: '9.3',
    term: 'Alloy',
    statement:
      'A mixture of a metal with one or more other elements, in which the different-sized atoms prevent the layers sliding, making it harder than the pure metal.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '11.1',
    term: 'Homologous series',
    statement:
      'A family of compounds with the same functional group and general formula, whose successive members differ by CH₂ and which show a gradual change in physical properties.',
  },
  { subject: 'chemistry', subtopicNumber: '11.4', term: 'Saturated hydrocarbon', statement: 'A hydrocarbon containing only single carbon–carbon bonds.' },
  { subject: 'chemistry', subtopicNumber: '11.5', term: 'Unsaturated hydrocarbon', statement: 'A hydrocarbon containing at least one carbon–carbon double bond.' },
  {
    subject: 'chemistry',
    subtopicNumber: '11.5',
    term: 'Cracking',
    statement:
      'The breaking down of large, less useful hydrocarbon molecules into smaller, more useful ones using heat and a catalyst.',
  },
  {
    subject: 'chemistry',
    subtopicNumber: '11.8',
    term: 'Addition polymerisation',
    statement: 'The joining together of many unsaturated monomer molecules to form a single long-chain polymer, with no other product.',
  },

  // --- Biology -------------------------------------------------------------
  {
    subject: 'biology',
    subtopicNumber: '3.1',
    term: 'Diffusion',
    statement: 'The net movement of particles from a region of higher concentration to a region of lower concentration, down a concentration gradient, as a result of their random motion.',
    examWording: 'Net movement, down a concentration gradient, due to random motion. No energy from respiration is required.',
  },
  {
    subject: 'biology',
    subtopicNumber: '3.1',
    term: 'Osmosis',
    statement: 'The net movement of water molecules from a region of higher water concentration to a region of lower water concentration, through a partially permeable membrane.',
    examWording: 'Three separately marked parts: net movement of water molecules; higher to lower water concentration; through a partially permeable membrane.',
  },
  {
    subject: 'biology',
    subtopicNumber: '3.2',
    term: 'Active transport',
    statement: 'The movement of particles through a cell membrane from a region of lower concentration to a region of higher concentration, using energy from respiration.',
    examWording: 'Against the concentration gradient, using energy released by respiration — both halves are needed.',
  },
  { subject: 'biology', subtopicNumber: '3.1', term: 'Turgid', statement: 'A plant cell that has taken in water by osmosis so that the vacuole pushes the cell contents firmly against the cell wall.' },
  { subject: 'biology', subtopicNumber: '3.1', term: 'Flaccid', statement: 'A plant cell that has lost water by osmosis so that it is no longer firm.' },
  { subject: 'biology', subtopicNumber: '5.1', term: 'Enzyme', statement: 'A protein that acts as a biological catalyst, speeding up a reaction without being changed itself.' },
  {
    subject: 'biology',
    subtopicNumber: '5.1',
    term: 'Denatured',
    statement: 'An enzyme whose shape has been permanently changed so that its active site no longer fits the substrate.',
    examWording: 'The active site changes shape, so the substrate no longer fits. Never write that the enzyme is "killed" — enzymes are not alive.',
  },
  { subject: 'biology', subtopicNumber: '5.1', term: 'Active site', statement: 'The region of an enzyme with a shape complementary to its specific substrate.' },
  {
    subject: 'biology',
    subtopicNumber: '6.1',
    term: 'Photosynthesis',
    statement: 'The process by which plants make glucose from carbon dioxide and water, using energy transferred from light and absorbed by chlorophyll.',
    examWording: 'Energy is transferred from light, not "made from" light. Chlorophyll absorbs it and is not used up.',
  },
  {
    subject: 'biology',
    subtopicNumber: '6.1',
    term: 'Limiting factor',
    statement: 'The factor present in the shortest supply, which alone determines the rate of a process at that moment.',
  },
  {
    subject: 'biology',
    subtopicNumber: '12.1',
    term: 'Respiration',
    statement: 'The chemical reactions in cells that break down nutrient molecules and release energy for metabolism.',
    examWording: 'Energy is released, never produced or created. The mark scheme is strict on this wording.',
  },
  { subject: 'biology', subtopicNumber: '12.1', term: 'Aerobic respiration', statement: 'The chemical reactions in cells that use oxygen to break down nutrient molecules and release energy.' },
  { subject: 'biology', subtopicNumber: '12.1', term: 'Anaerobic respiration', statement: 'The chemical reactions in cells that break down nutrient molecules without oxygen, releasing a much smaller amount of energy.' },
  { subject: 'biology', subtopicNumber: '8.1', term: 'Transpiration', statement: 'The loss of water vapour from the leaves of a plant by evaporation and diffusion through the stomata.' },
  { subject: 'biology', subtopicNumber: '8.1', term: 'Translocation', statement: 'The movement of sucrose and amino acids in phloem, from regions of production to regions of storage or use.' },
  { subject: 'biology', subtopicNumber: '10.1', term: 'Pathogen', statement: 'A disease-causing organism.' },
  { subject: 'biology', subtopicNumber: '14.1', term: 'Reflex action', statement: 'A means of automatically and rapidly integrating and coordinating stimuli with the responses of effectors.' },
  { subject: 'biology', subtopicNumber: '14.2', term: 'Homeostasis', statement: 'The maintenance of a constant internal environment.' },
  { subject: 'biology', subtopicNumber: '14.2', term: 'Hormone', statement: 'A chemical substance produced by a gland and carried by the blood, which alters the activity of one or more specific target organs.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Genotype', statement: 'The genetic make-up of an organism in terms of the alleles present.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Phenotype', statement: 'The observable features of an organism.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Allele', statement: 'A different version of a gene.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Dominant allele', statement: 'An allele that is expressed if it is present in the genotype.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Recessive allele', statement: 'An allele that is only expressed when there is no dominant allele of the same gene present.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Homozygous', statement: 'Having two identical alleles of a particular gene.' },
  { subject: 'biology', subtopicNumber: '17.1', term: 'Heterozygous', statement: 'Having two different alleles of a particular gene.' },
  { subject: 'biology', subtopicNumber: '17.3', term: 'Mitosis', statement: 'Nuclear division giving rise to genetically identical cells, used for growth, repair and asexual reproduction.' },
  { subject: 'biology', subtopicNumber: '17.3', term: 'Meiosis', statement: 'Reduction division in which the chromosome number is halved from diploid to haploid, producing genetically different cells.' },
  { subject: 'biology', subtopicNumber: '18.1', term: 'Natural selection', statement: 'The process by which organisms better adapted to their environment survive, reproduce and pass on their alleles to the next generation.' },
  { subject: 'biology', subtopicNumber: '18.1', term: 'Adaptation', statement: 'An inherited feature that helps an organism to survive and reproduce in its environment.' },
  { subject: 'biology', subtopicNumber: '19.1', term: 'Producer', statement: 'An organism that makes its own organic nutrients, usually using energy from light, by photosynthesis.' },
  { subject: 'biology', subtopicNumber: '19.1', term: 'Trophic level', statement: 'The position of an organism in a food chain, food web or pyramid of biomass.' },
  { subject: 'biology', subtopicNumber: '19.3', term: 'Population', statement: 'A group of organisms of one species living in the same area at the same time.' },
  { subject: 'biology', subtopicNumber: '1.1', term: 'Excretion', statement: 'The removal from organisms of the waste products of metabolism, toxic materials and substances in excess of requirements.' },

  // --- ICT -----------------------------------------------------------------
  {
    subject: 'ict',
    subtopicNumber: '18.2',
    term: 'Validation',
    statement: 'An automatic check carried out by a computer that data entered is sensible and within acceptable limits.',
    examWording: 'Validation checks that data is REASONABLE. It cannot check that the data is correct.',
  },
  {
    subject: 'ict',
    subtopicNumber: '18.2',
    term: 'Verification',
    statement: 'A check that data has been entered accurately and matches the original source.',
    examWording: 'Two accepted methods: double entry, and a visual check against the original document.',
  },
  { subject: 'ict', subtopicNumber: '18.2', term: 'Range check', statement: 'A validation check that data falls between an acceptable upper and lower limit.' },
  { subject: 'ict', subtopicNumber: '18.2', term: 'Presence check', statement: 'A validation check that a required field has not been left blank.' },
  { subject: 'ict', subtopicNumber: '18.1', term: 'Primary key', statement: 'A field that uniquely identifies each record in a database table.' },
  { subject: 'ict', subtopicNumber: '18.1', term: 'Field', statement: 'A single item of data in a record, forming one column of a database table.' },
  { subject: 'ict', subtopicNumber: '18.1', term: 'Record', statement: 'A complete set of fields about one person or thing, forming one row of a database table.' },
  { subject: 'ict', subtopicNumber: '4.1', term: 'LAN', statement: 'A local area network — computers connected over a small geographical area, such as one building or site.' },
  { subject: 'ict', subtopicNumber: '4.1', term: 'WAN', statement: 'A wide area network — computers or networks connected over a large geographical area, often using third-party communication links.' },
  {
    subject: 'ict',
    subtopicNumber: '4.1',
    term: 'The internet',
    statement: 'The global network of interconnected computer networks.',
    examWording: 'The internet is the infrastructure; the World Wide Web is one service running on it. They are not interchangeable.',
  },
  { subject: 'ict', subtopicNumber: '4.1', term: 'World Wide Web', statement: 'The collection of web pages and other resources accessed over the internet using HTTP.' },
  { subject: 'ict', subtopicNumber: '4.1', term: 'Router', statement: 'A device that directs data packets between networks and connects a LAN to a WAN.' },
  {
    subject: 'ict',
    subtopicNumber: '8.1',
    term: 'Phishing',
    statement: 'Sending a fraudulent message that appears to come from a legitimate organisation, to trick the recipient into revealing personal details.',
    examWording: 'Phishing needs the user to act — to click a link or reply. Pharming does not.',
  },
  { subject: 'ict', subtopicNumber: '8.1', term: 'Pharming', statement: 'Malicious code that redirects a user to a fake website even when the correct address has been typed.' },
  { subject: 'ict', subtopicNumber: '8.1', term: 'Firewall', statement: 'Hardware or software that monitors traffic entering and leaving a network against a set of rules and blocks anything unauthorised.' },
  { subject: 'ict', subtopicNumber: '8.1', term: 'Encryption', statement: 'Scrambling data using a key so that it is meaningless to anyone who intercepts it without that key.' },
  { subject: 'ict', subtopicNumber: '20.1', term: 'Absolute cell reference', statement: 'A spreadsheet reference fixed with dollar signs, which does not change when the formula is replicated.' },
  { subject: 'ict', subtopicNumber: '20.1', term: 'Relative cell reference', statement: 'A spreadsheet reference that changes to match its new position when the formula is replicated.' },
  { subject: 'ict', subtopicNumber: '3.1', term: 'Backup', statement: 'A second copy of data kept separately, so that data can be recovered if the original is lost or damaged.' },
  { subject: 'ict', subtopicNumber: '1.1', term: 'Hardware', statement: 'The physical components of a computer system.' },
  { subject: 'ict', subtopicNumber: '1.1', term: 'Software', statement: 'The programs that control a computer system and tell the hardware what to do.' },
  { subject: 'ict', subtopicNumber: '1.1', term: 'RAM', statement: 'Random access memory — volatile memory holding the data and programs currently in use, whose contents are lost when power is removed.' },
  { subject: 'ict', subtopicNumber: '1.1', term: 'ROM', statement: 'Read-only memory — non-volatile memory holding data that cannot normally be changed, such as the boot-up instructions.' },
  { subject: 'ict', subtopicNumber: '21.1', term: 'HTML', statement: 'The markup language used to define the structure and content of a web page.' },
  { subject: 'ict', subtopicNumber: '21.1', term: 'CSS', statement: 'The language used to define the presentation of a web page — its colours, fonts, sizes and layout.' },
  { subject: 'ict', subtopicNumber: '7.1', term: 'Normal test data', statement: 'Data within the acceptable range that the system should accept.' },
  { subject: 'ict', subtopicNumber: '7.1', term: 'Extreme test data', statement: 'Data at the very edge of the acceptable range, which the system should still accept.' },
  { subject: 'ict', subtopicNumber: '7.1', term: 'Abnormal test data', statement: 'Data outside the acceptable range or of the wrong type, which the system should reject.' },

  // --- Mathematics ---------------------------------------------------------
  { subject: 'maths', subtopicNumber: '1.1', term: 'Prime number', statement: 'A whole number greater than 1 with exactly two factors: 1 and itself.' },
  { subject: 'maths', subtopicNumber: '1.1', term: 'Highest common factor', statement: 'The largest number that divides exactly into two or more given numbers.' },
  { subject: 'maths', subtopicNumber: '1.1', term: 'Lowest common multiple', statement: 'The smallest number that is a multiple of two or more given numbers.' },
  {
    subject: 'maths',
    subtopicNumber: '1.5',
    term: 'Upper bound',
    statement: 'The largest value a rounded measurement could have had before rounding — half a unit of the last place value above the stated figure.',
    examWording: 'For a value given to 1 d.p. the bounds are ±0.05. For the upper bound of a difference, use the largest first value and the smallest second value.',
  },
  { subject: 'maths', subtopicNumber: '1.5', term: 'Lower bound', statement: 'The smallest value a rounded measurement could have had before rounding.' },
  {
    subject: 'maths',
    subtopicNumber: '2.5',
    term: 'Discriminant',
    statement: 'The expression b² − 4ac, which determines how many real roots a quadratic equation has.',
    examWording: 'Positive: two real roots. Zero: one repeated root. Negative: no real roots.',
  },
  { subject: 'maths', subtopicNumber: '4.3', term: 'Congruent', statement: 'Exactly the same shape and size, though possibly reflected or rotated.' },
  { subject: 'maths', subtopicNumber: '4.3', term: 'Similar', statement: 'The same shape but not necessarily the same size, with equal corresponding angles and corresponding sides in the same ratio.' },
  { subject: 'maths', subtopicNumber: '4.4', term: 'Locus', statement: 'The set of all points that satisfy a given rule or condition.' },
  { subject: 'maths', subtopicNumber: '4.4', term: 'Bearing', statement: 'An angle measured clockwise from north, always written with three figures.' },
  { subject: 'maths', subtopicNumber: '9.1', term: 'Median', statement: 'The middle value when the data are arranged in order.' },
  { subject: 'maths', subtopicNumber: '9.1', term: 'Mode', statement: 'The value that occurs most often.' },
  { subject: 'maths', subtopicNumber: '9.1', term: 'Mean', statement: 'The sum of the values divided by how many values there are.' },
  {
    subject: 'maths',
    subtopicNumber: '9.2',
    term: 'Interquartile range',
    statement: 'The upper quartile minus the lower quartile — the range of the middle 50% of the data.',
    examWording: 'Preferred to the range because it is not affected by extreme values or outliers.',
  },
  {
    subject: 'maths',
    subtopicNumber: '9.3',
    term: 'Frequency density',
    statement: 'Frequency divided by class width — the quantity plotted on the vertical axis of a histogram with unequal class widths.',
    examWording: 'In a histogram, frequency is represented by AREA, not by height.',
  },
  { subject: 'maths', subtopicNumber: '8.2', term: 'Relative frequency', statement: 'The number of times an outcome occurs divided by the total number of trials, used as an estimate of probability.' },
  { subject: 'maths', subtopicNumber: '1.6', term: 'Surd', statement: 'An irrational root that cannot be written exactly as a fraction, such as √2.' },
  { subject: 'maths', subtopicNumber: '2.8', term: 'Inverse function', statement: 'The function that reverses the effect of a given function, written f⁻¹(x).' },
  { subject: 'maths', subtopicNumber: '7.2', term: 'Vector', statement: 'A quantity with both magnitude and direction, written as a column of components.' },

  // --- Additional Mathematics ---------------------------------------------
  { subject: 'add-maths', subtopicNumber: '3.1', term: 'Stationary point', statement: 'A point on a curve where the gradient is zero, that is where dy/dx = 0.' },
  {
    subject: 'add-maths',
    subtopicNumber: '3.1',
    term: 'Second derivative test',
    statement: 'Evaluating d²y/dx² at a stationary point to determine its nature.',
    examWording: 'Negative second derivative means a maximum; positive means a minimum. A stationary point is not fully answered until its nature is determined.',
  },
  { subject: 'add-maths', subtopicNumber: '4.1', term: 'Definite integral', statement: 'An integral evaluated between two limits, giving a numerical value and requiring no constant of integration.' },
  {
    subject: 'add-maths',
    subtopicNumber: '4.1',
    term: 'Constant of integration',
    statement: 'The arbitrary constant c added to every indefinite integral, because differentiating any constant gives zero.',
    examWording: 'Omitting "+ c" is the most frequently dropped mark in the integration topic.',
  },
  { subject: 'add-maths', subtopicNumber: '1.1', term: 'Composite function', statement: 'A function formed by applying one function to the result of another; fg(x) means apply g first, then f.' },

  // --- International Mathematics ------------------------------------------
  { subject: 'intl-maths', subtopicNumber: '1.1', term: 'Union', statement: 'A ∪ B — the set of all elements that are in A, in B, or in both.' },
  { subject: 'intl-maths', subtopicNumber: '1.1', term: 'Intersection', statement: 'A ∩ B — the set of elements that are in both A and B.' },
  { subject: 'intl-maths', subtopicNumber: '1.1', term: 'Complement', statement: 'A′ — the set of all elements in the universal set that are not in A.' },
  { subject: 'intl-maths', subtopicNumber: '3.1', term: 'Mathematical model', statement: 'A mathematical description of a real situation, used to make predictions, whose assumptions limit how far it can be trusted.' },
];
