import type { FormulaSeed } from './types';

/**
 * The equation bank that powers the calculators, the formula sheets and the
 * "which equation do I need?" search. Each variable carries its unit so the
 * calculator can warn about incompatible inputs rather than silently producing
 * a wrong answer.
 */
export const formulas: FormulaSeed[] = [
  // --- Physics: motion, forces and energy ---------------------------------
  {
    key: 'speed',
    subject: 'physics',
    subtopicNumber: '1.2',
    name: 'Speed',
    expression: 'v = s / t',
    variables: [
      { symbol: 'v', label: 'Speed', unit: 'm/s', si: 'm/s' },
      { symbol: 's', label: 'Distance', unit: 'm', si: 'm' },
      { symbol: 't', label: 'Time', unit: 's', si: 's' },
    ],
    resultUnit: 'm/s',
    notes: 'Use average speed when the motion is not uniform.',
  },
  {
    key: 'acceleration',
    subject: 'physics',
    subtopicNumber: '1.2',
    name: 'Acceleration',
    expression: 'a = Δv / t',
    variables: [
      { symbol: 'a', label: 'Acceleration', unit: 'm/s²', si: 'm/s^2' },
      { symbol: 'Δv', label: 'Change in velocity', unit: 'm/s', si: 'm/s' },
      { symbol: 't', label: 'Time taken', unit: 's', si: 's' },
    ],
    resultUnit: 'm/s²',
    notes: 'A negative value means deceleration in the chosen positive direction.',
  },
  {
    key: 'density',
    subject: 'physics',
    subtopicNumber: '1.4',
    name: 'Density',
    expression: 'ρ = m / V',
    variables: [
      { symbol: 'ρ', label: 'Density', unit: 'kg/m³', si: 'kg/m^3' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'V', label: 'Volume', unit: 'm³', si: 'm^3' },
    ],
    resultUnit: 'kg/m³',
    notes: 'g/cm³ is also acceptable — 1 g/cm³ = 1000 kg/m³.',
  },
  {
    key: 'weight',
    subject: 'physics',
    subtopicNumber: '1.3',
    name: 'Weight',
    expression: 'W = m g',
    variables: [
      { symbol: 'W', label: 'Weight', unit: 'N', si: 'N' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'g', label: 'Gravitational field strength', unit: 'N/kg', si: 'N/kg' },
    ],
    resultUnit: 'N',
    notes: 'On Earth g ≈ 9.8 N/kg; many papers allow 10 N/kg.',
  },
  {
    key: 'force',
    subject: 'physics',
    subtopicNumber: '1.5',
    name: "Newton's second law",
    expression: 'F = m a',
    variables: [
      { symbol: 'F', label: 'Resultant force', unit: 'N', si: 'N' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'a', label: 'Acceleration', unit: 'm/s²', si: 'm/s^2' },
    ],
    resultUnit: 'N',
    notes: 'F must be the resultant force, not a single force acting on the object.',
  },
  {
    key: 'moment',
    subject: 'physics',
    subtopicNumber: '1.5',
    name: 'Moment of a force',
    expression: 'M = F d',
    variables: [
      { symbol: 'M', label: 'Moment', unit: 'N m', si: 'N m' },
      { symbol: 'F', label: 'Force', unit: 'N', si: 'N' },
      { symbol: 'd', label: 'Perpendicular distance from the pivot', unit: 'm', si: 'm' },
    ],
    resultUnit: 'N m',
    notes: 'The distance must be measured perpendicular to the line of action of the force.',
  },
  {
    key: 'momentum',
    subject: 'physics',
    subtopicNumber: '1.6',
    name: 'Momentum',
    expression: 'p = m v',
    variables: [
      { symbol: 'p', label: 'Momentum', unit: 'kg m/s', si: 'kg m/s' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'v', label: 'Velocity', unit: 'm/s', si: 'm/s' },
    ],
    resultUnit: 'kg m/s',
  },
  {
    key: 'kinetic-energy',
    subject: 'physics',
    subtopicNumber: '1.7',
    name: 'Kinetic energy',
    expression: 'Ek = ½ m v²',
    variables: [
      { symbol: 'Ek', label: 'Kinetic energy', unit: 'J', si: 'J' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'v', label: 'Speed', unit: 'm/s', si: 'm/s' },
    ],
    resultUnit: 'J',
    notes: 'The speed is squared — doubling the speed quadruples the kinetic energy.',
  },
  {
    key: 'gravitational-pe',
    subject: 'physics',
    subtopicNumber: '1.7',
    name: 'Change in gravitational potential energy',
    expression: 'ΔEp = m g Δh',
    variables: [
      { symbol: 'ΔEp', label: 'Change in g.p.e.', unit: 'J', si: 'J' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'g', label: 'Gravitational field strength', unit: 'N/kg', si: 'N/kg' },
      { symbol: 'Δh', label: 'Change in height', unit: 'm', si: 'm' },
    ],
    resultUnit: 'J',
  },
  {
    key: 'work',
    subject: 'physics',
    subtopicNumber: '1.7',
    name: 'Work done',
    expression: 'W = F d',
    variables: [
      { symbol: 'W', label: 'Work done', unit: 'J', si: 'J' },
      { symbol: 'F', label: 'Force', unit: 'N', si: 'N' },
      { symbol: 'd', label: 'Distance moved in the direction of the force', unit: 'm', si: 'm' },
    ],
    resultUnit: 'J',
  },
  {
    key: 'power',
    subject: 'physics',
    subtopicNumber: '1.7',
    name: 'Power',
    expression: 'P = E / t',
    variables: [
      { symbol: 'P', label: 'Power', unit: 'W', si: 'W' },
      { symbol: 'E', label: 'Energy transferred (or work done)', unit: 'J', si: 'J' },
      { symbol: 't', label: 'Time', unit: 's', si: 's' },
    ],
    resultUnit: 'W',
  },
  {
    key: 'efficiency',
    subject: 'physics',
    subtopicNumber: '1.7',
    name: 'Efficiency',
    expression: 'efficiency = useful output energy / total input energy',
    variables: [
      { symbol: 'Eout', label: 'Useful output energy', unit: 'J', si: 'J' },
      { symbol: 'Ein', label: 'Total input energy', unit: 'J', si: 'J' },
    ],
    resultUnit: '(no unit — multiply by 100 for %)',
    notes: 'Efficiency can never exceed 1 (100%). If it does, the fraction is upside down.',
  },
  {
    key: 'pressure',
    subject: 'physics',
    subtopicNumber: '1.8',
    name: 'Pressure',
    expression: 'p = F / A',
    variables: [
      { symbol: 'p', label: 'Pressure', unit: 'Pa', si: 'Pa' },
      { symbol: 'F', label: 'Force', unit: 'N', si: 'N' },
      { symbol: 'A', label: 'Area', unit: 'm²', si: 'm^2' },
    ],
    resultUnit: 'Pa',
    notes: '1 Pa = 1 N/m².',
  },
  {
    key: 'liquid-pressure',
    subject: 'physics',
    subtopicNumber: '1.8',
    name: 'Pressure difference in a liquid',
    expression: 'Δp = ρ g Δh',
    variables: [
      { symbol: 'Δp', label: 'Pressure difference', unit: 'Pa', si: 'Pa' },
      { symbol: 'ρ', label: 'Density of the liquid', unit: 'kg/m³', si: 'kg/m^3' },
      { symbol: 'g', label: 'Gravitational field strength', unit: 'N/kg', si: 'N/kg' },
      { symbol: 'Δh', label: 'Change in depth', unit: 'm', si: 'm' },
    ],
    resultUnit: 'Pa',
  },

  // --- Physics: thermal ----------------------------------------------------
  {
    key: 'boyles-law',
    subject: 'physics',
    subtopicNumber: '2.1',
    name: 'Pressure and volume of a fixed mass of gas',
    expression: 'p₁ V₁ = p₂ V₂',
    variables: [
      { symbol: 'p₁', label: 'Initial pressure', unit: 'Pa', si: 'Pa' },
      { symbol: 'V₁', label: 'Initial volume', unit: 'm³', si: 'm^3' },
      { symbol: 'p₂', label: 'Final pressure', unit: 'Pa', si: 'Pa' },
      { symbol: 'V₂', label: 'Final volume', unit: 'm³', si: 'm^3' },
    ],
    resultUnit: 'depends on the unknown',
    notes: 'Only valid at constant temperature for a fixed mass of gas.',
  },
  {
    key: 'specific-heat',
    subject: 'physics',
    subtopicNumber: '2.2',
    name: 'Specific heat capacity',
    expression: 'E = m c Δθ',
    variables: [
      { symbol: 'E', label: 'Energy transferred', unit: 'J', si: 'J' },
      { symbol: 'm', label: 'Mass', unit: 'kg', si: 'kg' },
      { symbol: 'c', label: 'Specific heat capacity', unit: 'J/(kg °C)', si: 'J/(kg K)' },
      { symbol: 'Δθ', label: 'Temperature change', unit: '°C', si: 'K' },
    ],
    resultUnit: 'J',
    notes: 'Water has c = 4200 J/(kg °C).',
  },

  // --- Physics: waves ------------------------------------------------------
  {
    key: 'wave-equation',
    subject: 'physics',
    subtopicNumber: '3.1',
    name: 'Wave equation',
    expression: 'v = f λ',
    variables: [
      { symbol: 'v', label: 'Wave speed', unit: 'm/s', si: 'm/s' },
      { symbol: 'f', label: 'Frequency', unit: 'Hz', si: 'Hz' },
      { symbol: 'λ', label: 'Wavelength', unit: 'm', si: 'm' },
    ],
    resultUnit: 'm/s',
  },
  {
    key: 'time-period',
    subject: 'physics',
    subtopicNumber: '3.1',
    name: 'Time period and frequency',
    expression: 'T = 1 / f',
    variables: [
      { symbol: 'T', label: 'Time period', unit: 's', si: 's' },
      { symbol: 'f', label: 'Frequency', unit: 'Hz', si: 'Hz' },
    ],
    resultUnit: 's',
  },
  {
    key: 'refractive-index',
    subject: 'physics',
    subtopicNumber: '3.2',
    name: 'Refractive index',
    expression: 'n = sin i / sin r',
    variables: [
      { symbol: 'n', label: 'Refractive index', unit: '(none)', si: '' },
      { symbol: 'i', label: 'Angle of incidence', unit: '°', si: 'deg' },
      { symbol: 'r', label: 'Angle of refraction', unit: '°', si: 'deg' },
    ],
    resultUnit: '(no unit)',
    notes: 'Angles are always measured from the normal, never from the surface.',
  },

  // --- Physics: electricity -----------------------------------------------
  {
    key: 'current',
    subject: 'physics',
    subtopicNumber: '4.2',
    name: 'Current and charge',
    expression: 'I = Q / t',
    variables: [
      { symbol: 'I', label: 'Current', unit: 'A', si: 'A' },
      { symbol: 'Q', label: 'Charge', unit: 'C', si: 'C' },
      { symbol: 't', label: 'Time', unit: 's', si: 's' },
    ],
    resultUnit: 'A',
  },
  {
    key: 'potential-difference',
    subject: 'physics',
    subtopicNumber: '4.2',
    name: 'Potential difference',
    expression: 'V = E / Q',
    variables: [
      { symbol: 'V', label: 'Potential difference', unit: 'V', si: 'V' },
      { symbol: 'E', label: 'Energy transferred', unit: 'J', si: 'J' },
      { symbol: 'Q', label: 'Charge', unit: 'C', si: 'C' },
    ],
    resultUnit: 'V',
    notes: 'One volt is one joule per coulomb.',
  },
  {
    key: 'ohms-law',
    subject: 'physics',
    subtopicNumber: '4.2',
    name: "Ohm's law",
    expression: 'V = I R',
    variables: [
      { symbol: 'V', label: 'Potential difference', unit: 'V', si: 'V' },
      { symbol: 'I', label: 'Current', unit: 'A', si: 'A' },
      { symbol: 'R', label: 'Resistance', unit: 'Ω', si: 'ohm' },
    ],
    resultUnit: 'V',
    notes: 'Valid for a metallic conductor at constant temperature.',
  },
  {
    key: 'electrical-power',
    subject: 'physics',
    subtopicNumber: '4.2',
    name: 'Electrical power',
    expression: 'P = I V',
    variables: [
      { symbol: 'P', label: 'Power', unit: 'W', si: 'W' },
      { symbol: 'I', label: 'Current', unit: 'A', si: 'A' },
      { symbol: 'V', label: 'Potential difference', unit: 'V', si: 'V' },
    ],
    resultUnit: 'W',
    notes: 'Combining with V = IR gives P = I²R, used for transmission losses.',
  },
  {
    key: 'electrical-energy',
    subject: 'physics',
    subtopicNumber: '4.2',
    name: 'Electrical energy',
    expression: 'E = I V t',
    variables: [
      { symbol: 'E', label: 'Energy transferred', unit: 'J', si: 'J' },
      { symbol: 'I', label: 'Current', unit: 'A', si: 'A' },
      { symbol: 'V', label: 'Potential difference', unit: 'V', si: 'V' },
      { symbol: 't', label: 'Time', unit: 's', si: 's' },
    ],
    resultUnit: 'J',
  },
  {
    key: 'transformer',
    subject: 'physics',
    subtopicNumber: '4.5',
    name: 'Transformer turns ratio',
    expression: 'Vp / Vs = Np / Ns',
    variables: [
      { symbol: 'Vp', label: 'Primary voltage', unit: 'V', si: 'V' },
      { symbol: 'Vs', label: 'Secondary voltage', unit: 'V', si: 'V' },
      { symbol: 'Np', label: 'Turns on the primary', unit: '(count)', si: '' },
      { symbol: 'Ns', label: 'Turns on the secondary', unit: '(count)', si: '' },
    ],
    resultUnit: 'depends on the unknown',
    notes: 'For an ideal transformer, VpIp = VsIs.',
  },

  // --- Physics: space ------------------------------------------------------
  {
    key: 'orbital-speed',
    subject: 'physics',
    subtopicNumber: '6.1',
    name: 'Orbital speed',
    expression: 'v = 2πr / T',
    variables: [
      { symbol: 'v', label: 'Orbital speed', unit: 'm/s', si: 'm/s' },
      { symbol: 'r', label: 'Orbital radius', unit: 'm', si: 'm' },
      { symbol: 'T', label: 'Orbital period', unit: 's', si: 's' },
    ],
    resultUnit: 'm/s',
  },

  // --- Chemistry -----------------------------------------------------------
  {
    key: 'moles-from-mass',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Moles from mass',
    expression: 'n = m / Mr',
    variables: [
      { symbol: 'n', label: 'Amount of substance', unit: 'mol', si: 'mol' },
      { symbol: 'm', label: 'Mass', unit: 'g', si: 'g' },
      { symbol: 'Mr', label: 'Relative formula mass', unit: '(none)', si: '' },
    ],
    resultUnit: 'mol',
  },
  {
    key: 'concentration',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Concentration',
    expression: 'c = n / V',
    variables: [
      { symbol: 'c', label: 'Concentration', unit: 'mol/dm³', si: 'mol/dm^3' },
      { symbol: 'n', label: 'Amount of substance', unit: 'mol', si: 'mol' },
      { symbol: 'V', label: 'Volume of solution', unit: 'dm³', si: 'dm^3' },
    ],
    resultUnit: 'mol/dm³',
    notes: '1 dm³ = 1000 cm³. Converting volume is the most common source of error.',
  },
  {
    key: 'gas-volume',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Volume of a gas at r.t.p.',
    expression: 'V = n × 24',
    variables: [
      { symbol: 'V', label: 'Volume of gas', unit: 'dm³', si: 'dm^3' },
      { symbol: 'n', label: 'Amount of substance', unit: 'mol', si: 'mol' },
    ],
    resultUnit: 'dm³',
    notes: 'One mole of any gas occupies 24 dm³ at room temperature and pressure.',
  },
  {
    key: 'particles',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Number of particles',
    expression: 'N = n × 6.02 × 10²³',
    variables: [
      { symbol: 'N', label: 'Number of particles', unit: '(count)', si: '' },
      { symbol: 'n', label: 'Amount of substance', unit: 'mol', si: 'mol' },
    ],
    resultUnit: 'particles',
    notes: 'The Avogadro constant is 6.02 × 10²³ per mole.',
  },
  {
    key: 'mass-concentration',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Concentration in g/dm³',
    expression: 'concentration (g/dm³) = concentration (mol/dm³) × Mr',
    variables: [
      { symbol: 'cg', label: 'Concentration by mass', unit: 'g/dm³', si: 'g/dm^3' },
      { symbol: 'c', label: 'Concentration', unit: 'mol/dm³', si: 'mol/dm^3' },
      { symbol: 'Mr', label: 'Relative formula mass', unit: '(none)', si: '' },
    ],
    resultUnit: 'g/dm³',
  },
  {
    key: 'percentage-yield',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Percentage yield',
    expression: '% yield = (actual yield / theoretical yield) × 100',
    variables: [
      { symbol: 'actual', label: 'Actual yield', unit: 'g', si: 'g' },
      { symbol: 'theoretical', label: 'Theoretical yield', unit: 'g', si: 'g' },
    ],
    resultUnit: '%',
    notes: 'A yield above 100% means the product is impure or still wet.',
  },
  {
    key: 'percentage-purity',
    subject: 'chemistry',
    subtopicNumber: '3.3',
    name: 'Percentage purity',
    expression: '% purity = (mass of pure substance / mass of sample) × 100',
    variables: [
      { symbol: 'pure', label: 'Mass of pure substance', unit: 'g', si: 'g' },
      { symbol: 'sample', label: 'Mass of impure sample', unit: 'g', si: 'g' },
    ],
    resultUnit: '%',
  },
  {
    key: 'rf-value',
    subject: 'chemistry',
    subtopicNumber: '12.3',
    name: 'Rf value',
    expression: 'Rf = distance moved by substance / distance moved by solvent',
    variables: [
      { symbol: 'ds', label: 'Distance moved by the substance', unit: 'cm', si: 'cm' },
      { symbol: 'df', label: 'Distance moved by the solvent front', unit: 'cm', si: 'cm' },
    ],
    resultUnit: '(no unit)',
    notes: 'Rf is always between 0 and 1.',
  },

  // --- Biology -------------------------------------------------------------
  {
    key: 'magnification',
    subject: 'biology',
    subtopicNumber: '2.3',
    name: 'Magnification',
    expression: 'M = image size / actual size',
    variables: [
      { symbol: 'I', label: 'Image size, as drawn or photographed', unit: 'mm', si: 'mm' },
      { symbol: 'A', label: 'Actual size of the specimen', unit: 'mm', si: 'mm' },
    ],
    resultUnit: '× (no unit)',
    notes:
      'Both lengths must be in the same unit before dividing — converting one of them is the step most often missed. Rearrange to A = I / M to find the real size.',
  },
  {
    key: 'percentage-change-mass',
    subject: 'biology',
    subtopicNumber: '3.1',
    name: 'Percentage change in mass',
    expression: '% change = (final − initial) / initial × 100',
    variables: [
      { symbol: 'mf', label: 'Final mass', unit: 'g', si: 'g' },
      { symbol: 'mi', label: 'Initial mass', unit: 'g', si: 'g' },
    ],
    resultUnit: '%',
    notes:
      'Used for osmosis practicals. Divide by the INITIAL mass, and keep the sign — a negative value means water left the tissue.',
  },
  {
    key: 'energy-transfer-efficiency',
    subject: 'biology',
    subtopicNumber: '19.1',
    name: 'Efficiency of energy transfer',
    expression: 'efficiency = energy at the next trophic level / energy at the previous level × 100',
    variables: [
      { symbol: 'En', label: 'Energy at the next trophic level', unit: 'kJ', si: 'kJ' },
      { symbol: 'Ep', label: 'Energy at the previous trophic level', unit: 'kJ', si: 'kJ' },
    ],
    resultUnit: '%',
    notes:
      'Typically about 10%. The rest is lost as heat from respiration, in movement, and in faeces and urine.',
  },

  // --- Mathematics ---------------------------------------------------------
  {
    key: 'circle-area',
    subject: 'maths',
    subtopicNumber: '5.1',
    name: 'Area of a circle',
    expression: 'A = πr²',
    variables: [{ symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' }],
    resultUnit: 'cm²',
    notes: 'If the question gives the diameter, halve it first — using d for r makes the answer four times too big.',
  },
  {
    key: 'circle-circumference',
    subject: 'maths',
    subtopicNumber: '5.1',
    name: 'Circumference of a circle',
    expression: 'C = 2πr = πd',
    variables: [{ symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' }],
    resultUnit: 'cm',
  },
  {
    key: 'arc-length',
    subject: 'maths',
    subtopicNumber: '5.2',
    name: 'Arc length',
    expression: 'arc = (θ / 360) × 2πr',
    variables: [
      { symbol: 'θ', label: 'Angle at the centre', unit: '°', si: '°' },
      { symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' },
    ],
    resultUnit: 'cm',
    notes: 'A sector is a fraction of the whole circle, and θ/360 is that fraction.',
  },
  {
    key: 'sector-area',
    subject: 'maths',
    subtopicNumber: '5.2',
    name: 'Area of a sector',
    expression: 'A = (θ / 360) × πr²',
    variables: [
      { symbol: 'θ', label: 'Angle at the centre', unit: '°', si: '°' },
      { symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' },
    ],
    resultUnit: 'cm²',
  },
  {
    key: 'cylinder-volume',
    subject: 'maths',
    subtopicNumber: '5.1',
    name: 'Volume of a cylinder',
    expression: 'V = πr²h',
    variables: [
      { symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' },
      { symbol: 'h', label: 'Height', unit: 'cm', si: 'cm' },
    ],
    resultUnit: 'cm³',
  },
  {
    key: 'sphere-volume',
    subject: 'maths',
    subtopicNumber: '5.1',
    name: 'Volume of a sphere',
    expression: 'V = (4/3)πr³',
    variables: [{ symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' }],
    resultUnit: 'cm³',
    notes: 'Given on the formula sheet in the exam, but you still have to know which one to reach for.',
  },
  {
    key: 'cone-volume',
    subject: 'maths',
    subtopicNumber: '5.1',
    name: 'Volume of a cone',
    expression: 'V = (1/3)πr²h',
    variables: [
      { symbol: 'r', label: 'Radius', unit: 'cm', si: 'cm' },
      { symbol: 'h', label: 'Perpendicular height', unit: 'cm', si: 'cm' },
    ],
    resultUnit: 'cm³',
    notes:
      'h is the perpendicular height, not the slant height — the slant height belongs to the curved surface area formula.',
  },
  {
    key: 'pythagoras',
    subject: 'maths',
    subtopicNumber: '6.1',
    name: 'Pythagoras’ theorem',
    expression: 'a² + b² = c²',
    variables: [
      { symbol: 'a', label: 'One shorter side', unit: 'cm', si: 'cm' },
      { symbol: 'b', label: 'Other shorter side', unit: 'cm', si: 'cm' },
      { symbol: 'c', label: 'Hypotenuse, opposite the right angle', unit: 'cm', si: 'cm' },
    ],
    resultUnit: 'cm',
    notes: 'Right-angled triangles only. To find a shorter side, subtract rather than add: a² = c² − b².',
  },
  {
    key: 'sine-rule',
    subject: 'maths',
    subtopicNumber: '6.2',
    name: 'Sine rule',
    expression: 'a / sin A = b / sin B = c / sin C',
    variables: [
      { symbol: 'a', label: 'Side opposite angle A', unit: 'cm', si: 'cm' },
      { symbol: 'A', label: 'Angle opposite side a', unit: '°', si: '°' },
    ],
    resultUnit: 'cm or °',
    notes: 'Use when you have a side and the angle opposite it. Turn it upside down when you are finding an angle.',
  },
  {
    key: 'cosine-rule',
    subject: 'maths',
    subtopicNumber: '6.2',
    name: 'Cosine rule',
    expression: 'a² = b² + c² − 2bc cos A',
    variables: [
      { symbol: 'a', label: 'Side opposite angle A', unit: 'cm', si: 'cm' },
      { symbol: 'b', label: 'Second side', unit: 'cm', si: 'cm' },
      { symbol: 'c', label: 'Third side', unit: 'cm', si: 'cm' },
      { symbol: 'A', label: 'Angle between sides b and c', unit: '°', si: '°' },
    ],
    resultUnit: 'cm',
    notes: 'Use when you have two sides and the angle between them, or all three sides.',
  },
  {
    key: 'triangle-area-sine',
    subject: 'maths',
    subtopicNumber: '6.2',
    name: 'Area of a triangle',
    expression: 'A = ½ab sin C',
    variables: [
      { symbol: 'a', label: 'First side', unit: 'cm', si: 'cm' },
      { symbol: 'b', label: 'Second side', unit: 'cm', si: 'cm' },
      { symbol: 'C', label: 'Angle between them', unit: '°', si: '°' },
    ],
    resultUnit: 'cm²',
    notes: 'C must be the angle BETWEEN the two sides you use.',
  },
  {
    key: 'quadratic-formula',
    subject: 'maths',
    subtopicNumber: '2.5',
    name: 'Quadratic formula',
    expression: 'x = (−b ± √(b² − 4ac)) / 2a',
    variables: [
      { symbol: 'a', label: 'Coefficient of x²', unit: '', si: '' },
      { symbol: 'b', label: 'Coefficient of x', unit: '', si: '' },
      { symbol: 'c', label: 'Constant term', unit: '', si: '' },
    ],
    resultUnit: '(no unit)',
    notes:
      'Reach for this when the question asks for decimal places — that is a hint the quadratic will not factorise. The whole numerator is divided by 2a.',
  },
  {
    key: 'compound-interest',
    subject: 'maths',
    subtopicNumber: '1.4',
    name: 'Compound interest',
    expression: 'V = P × (1 + r/100)ⁿ',
    variables: [
      { symbol: 'P', label: 'Principal, the starting amount', unit: '', si: '' },
      { symbol: 'r', label: 'Interest rate per period', unit: '%', si: '%' },
      { symbol: 'n', label: 'Number of periods', unit: '', si: '' },
    ],
    resultUnit: '(currency)',
    notes:
      'For depreciation use (1 − r/100)ⁿ. The result is the total value — subtract P to get the interest alone.',
  },
  {
    key: 'gradient',
    subject: 'maths',
    subtopicNumber: '3.1',
    name: 'Gradient of a straight line',
    expression: 'm = (y₂ − y₁) / (x₂ − x₁)',
    variables: [
      { symbol: 'x', label: 'x-coordinates', unit: '', si: '' },
      { symbol: 'y', label: 'y-coordinates', unit: '', si: '' },
    ],
    resultUnit: '(no unit)',
    notes: 'Change in y over change in x — subtract the coordinates in the same order top and bottom.',
  },

  // --- Additional Mathematics ---------------------------------------------
  {
    key: 'derivative-power',
    subject: 'add-maths',
    subtopicNumber: '3.1',
    name: 'Differentiating a power of x',
    expression: 'd/dx (axⁿ) = anxⁿ⁻¹',
    variables: [
      { symbol: 'a', label: 'Coefficient', unit: '', si: '' },
      { symbol: 'n', label: 'Power', unit: '', si: '' },
    ],
    resultUnit: '(no unit)',
    notes: 'Multiply by the power, then reduce the power by one.',
  },
  {
    key: 'integral-power',
    subject: 'add-maths',
    subtopicNumber: '4.1',
    name: 'Integrating a power of x',
    expression: '∫ axⁿ dx = axⁿ⁺¹ / (n + 1) + c',
    variables: [
      { symbol: 'a', label: 'Coefficient', unit: '', si: '' },
      { symbol: 'n', label: 'Power, where n ≠ −1', unit: '', si: '' },
    ],
    resultUnit: '(no unit)',
    notes:
      'Raise the power by one, divide by the new power, and never omit the + c on an indefinite integral.',
  },
  {
    key: 'trig-identity-pythagorean',
    subject: 'add-maths',
    subtopicNumber: '5.1',
    name: 'Pythagorean identity',
    expression: 'sin²θ + cos²θ = 1',
    variables: [{ symbol: 'θ', label: 'Angle', unit: '°', si: '°' }],
    resultUnit: '(no unit)',
    notes:
      'Rearranges to sin²θ = 1 − cos²θ, which is how most trigonometric equations are reduced to a single function.',
  },
];
