import {
  AlertTriangle,
  Atom,
  BookOpen,
  Calculator,
  CalendarCheck,
  Camera,
  FlaskConical,
  Globe,
  Grid3x3,
  Infinity as InfinityIcon,
  LayoutDashboard,
  Layers,
  Leaf,
  Lightbulb,
  Mic,
  MonitorSmartphone,
  Network,
  NotebookPen,
  PenLine,
  PlayCircle,
  Shapes,
  Sigma,
  Sparkles,
  TrendingUp,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Explicit map rather than dynamic lookup, so icons are tree-shaken properly. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  AlertTriangle,
  Atom,
  BookOpen,
  Calculator,
  CalendarCheck,
  Camera,
  FlaskConical,
  Globe,
  Grid3x3,
  Infinity: InfinityIcon,
  LayoutDashboard,
  Layers,
  Leaf,
  Lightbulb,
  Mic,
  MonitorSmartphone,
  Network,
  NotebookPen,
  PenLine,
  PlayCircle,
  Shapes,
  Sigma,
  Sparkles,
  TrendingUp,
  Zap,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = NAV_ICONS[name] ?? Sparkles;
  return <Icon className={className} aria-hidden="true" />;
}
